// Bharat Sant Darshan - Saints Database
// Focus: Sanatan Dharma (Hindu, Sikh, Jain traditions)

const TRADITIONS = {
    hindu: {
        id: 'hindu',
        name: 'Hindu Saints',
        nameHi: 'हिंदू संत',
        icon: 'fa-om',
        color: '#FF9933',
        description: 'Bhakti and Vedantic saints across sampradayas'
    },
    sikh: {
        id: 'sikh',
        name: 'Sikh Gurus & Bhagats',
        nameHi: 'सिख गुरु',
        icon: 'fa-khanda',
        color: '#1E90FF',
        description: 'The Ten Gurus and the Bhagats of Guru Granth Sahib'
    },
    jain: {
        id: 'jain',
        name: 'Jain Tirthankaras',
        nameHi: 'जैन तीर्थंकर',
        icon: 'fa-hand',
        color: '#FFD700',
        description: 'The 24 ford-makers and great Acharyas'
    },
    buddhist: {
        id: 'buddhist',
        name: 'Buddhist Masters',
        nameHi: 'बौद्ध आचार्य',
        icon: 'fa-dharmachakra',
        color: '#8B5CF6',
        description: 'Buddha (9th Vishnu Avatar) and the great masters of Dharma'
    }
};

const SAINTS = [
    // ========== HINDU - ALVARS ==========
    {
        id: 'nammalvar',
        name: 'Nammalvar',
        nameLocal: 'நம்மாழ்வார்',
        nameHi: 'नम्मालवार',
        tradition: 'hindu',
        sampradaya: 'Alvar',
        period: '8th-9th century CE',
        birthPlace: 'Alwarthirunagari, Tamil Nadu',
        biography: 'Nammalvar is considered the greatest among the twelve Alvars, the Vaishnavite poet-saints of South India. His magnum opus, the Tiruvaymoli (4000 verses), is revered as the "Tamil Veda" and forms the theological foundation of Sri Vaishnavism. Born into a Shudra family, he spent his early life in meditative silence under a tamarind tree before composing his devotional hymns.',
        teachings: ['Prapatti (surrender) to Vishnu', 'Bhakti transcends caste', 'God is both immanent and transcendent'],
        works: ['Tiruvaymoli', 'Tiruviruttam', 'Thiruvasiriyam', 'Periya Thiruvandhadhi'],
        quotes: ['"The Lord dwells in the heart of those who love Him."', '"Through devotion alone, the soul reaches the Supreme."'],
        image: 'nammalvar.jpg'
    },
    {
        id: 'andal',
        name: 'Andal',
        nameLocal: 'ஆண்டாள்',
        nameHi: 'आण्डाल',
        tradition: 'hindu',
        sampradaya: 'Alvar',
        period: '8th century CE',
        birthPlace: 'Srivilliputhur, Tamil Nadu',
        biography: 'Andal is the only female Alvar and one of the most celebrated female saints in Hinduism. According to tradition, she was found as a baby under a tulsi plant by Periyalvar. She grew up composing passionate devotional poetry to Lord Vishnu, refusing to marry any mortal and considering herself the bride of Lord Ranganatha. Her Thiruppavai, sung during Margazhi month, remains immensely popular.',
        teachings: ['Bridal mysticism in devotion', 'Complete surrender to God', 'Love as the path to liberation'],
        works: ['Thiruppavai (30 verses)', 'Nachiar Thirumozhi (143 verses)'],
        quotes: ['"I will not marry a mortal; I belong only to Narayana."'],
        image: 'andal.jpg'
    },
    {
        id: 'periyalvar',
        name: 'Periyalvar',
        nameLocal: 'பெரியாழ்வார்',
        nameHi: 'पेरियाळ्वार',
        tradition: 'hindu',
        sampradaya: 'Alvar',
        period: '8th century CE',
        birthPlace: 'Srivilliputhur, Tamil Nadu',
        biography: 'Periyalvar (also called Vishnuchitta) was the father of Andal and one of the 12 Alvars. He won a debate at the Pandya court proving Vishnu as the Supreme and was honored by the king. Unique among Alvars, he approached God with parental love (Vatsalya Bhava), singing lullabies to Krishna. He composed the Tiruppallandu, which opens all Vaishnavite worship.',
        teachings: ['Vatsalya Bhava (parental devotion)', 'Krishna as a child', 'Temple rituals'],
        works: ['Tiruppallandu', 'Periyalvar Tirumoli'],
        quotes: ['"Pallandu pallandu pallayirathandu!" (May you live forever!)'],
        image: 'periyalvar.jpg'
    },
    {
        id: 'kulasekhara',
        name: 'Kulasekhara Alvar',
        nameLocal: 'குலசேகர ஆழ்வார்',
        nameHi: 'कुलशेखर आळ्वार',
        tradition: 'hindu',
        sampradaya: 'Alvar',
        period: '8th-9th century CE',
        birthPlace: 'Thiruvanjikkulam, Kerala',
        biography: 'Kulasekhara Alvar was the Chera king of Kerala who renounced his throne for devotion. His Perumal Tirumoli uniquely explores devotion through the perspectives of characters from epics - singing as Devaki missing Krishna, as Dasharatha longing for Rama. His Mukundamala is famous across India.',
        teachings: ['Devotion through role-playing', 'Royal renunciation', 'Surrender to Vishnu'],
        works: ['Perumal Tirumoli', 'Mukundamala'],
        quotes: ['"O Mukunda, grant me devotion to your lotus feet."'],
        image: 'kulasekhara.jpg'
    },
    {
        id: 'thirumangai',
        name: 'Thirumangai Alvar',
        nameLocal: 'திருமங்கையாழ்வார்',
        nameHi: 'तिरुमंगै आळ्वार',
        tradition: 'hindu',
        sampradaya: 'Alvar',
        period: '8th century CE',
        birthPlace: 'Thirukurayalur, Tamil Nadu',
        biography: 'Thirumangai Alvar, originally a chieftain named Kaliyan, is the most prolific Alvar with 1361 verses. Legend says he was a robber who converted after an encounter with Vishnu. He contributed six works to the Nalayira Divya Prabandham and is said to have built the walls of Srirangam temple using wealth from his earlier life.',
        teachings: ['Redemption through devotion', 'Temple service', 'Poetic excellence'],
        works: ['Periya Tirumoli', 'Tirukkurunthantakam', 'Tirunedunthantakam', 'Tiruvezhukurrirukkai', 'Siriya Tirumatal', 'Periya Tirumatal'],
        quotes: ['"The Lord accepted even a robber like me."'],
        image: 'thirumangai.jpg'
    },
    {
        id: 'poigai',
        name: 'Poigai Alvar',
        nameLocal: 'பொய்கையாழ்வார்',
        nameHi: 'पोयगै आळ्वार',
        tradition: 'hindu',
        sampradaya: 'Alvar',
        period: '7th century CE',
        birthPlace: 'Kanchipuram, Tamil Nadu',
        biography: 'Poigai Alvar is one of the Mudal Alvars (first three Alvars) who lived contemporaneously. According to legend, the three met on a stormy night in a tiny space, and as they squeezed together, they sensed a fourth divine presence - Vishnu. Poigai then lit the "lamp of earth with the sun as its flame" to see the Lord.',
        teachings: ['Intuitive God-realization', 'Poetry as worship', 'Nature as divine manifestation'],
        works: ['Mudal Tiruvandhadhi (100 verses)'],
        quotes: ['"I lit the lamp of the earth with the sun, to see my Lord."'],
        image: 'poigai.jpg'
    },
    {
        id: 'bhutath',
        name: 'Bhutath Alvar',
        nameLocal: 'பூதத்தாழ்வார்',
        nameHi: 'भूतत्ताळ्वार',
        tradition: 'hindu',
        sampradaya: 'Alvar',
        period: '7th century CE',
        birthPlace: 'Mahabalipuram, Tamil Nadu',
        biography: 'Bhutath Alvar (also Bhoothath) is the second of the Mudal Alvars. Present during the mystical night encounter, when Poigai lit the lamp of earth, Bhutath lit "the lamp of love with the mind as wick" to behold Vishnu. His 100 verses complement those of his companions.',
        teachings: ['Love as the light to see God', 'Spontaneous devotion', 'Unity of the Alvars'],
        works: ['Irandaam Tiruvandhadhi (100 verses)'],
        quotes: ['"Love is the wick; the mind the lamp; I see my Lord."'],
        image: 'bhutath.jpg'
    },
    {
        id: 'pey',
        name: 'Pey Alvar',
        nameLocal: 'பேயாழ்வார்',
        nameHi: 'पेय आळ्वार',
        tradition: 'hindu',
        sampradaya: 'Alvar',
        period: '7th century CE',
        birthPlace: 'Mylapore, Chennai',
        biography: 'Pey Alvar is the third of the Mudal Alvars. Completing the trio on that mystical night, he lit "the lamp of knowledge with devotion as the ghee." He describes the vision of Vishnu with Lakshmi appearing before the three saints. His name "Pey" (meaning madman) reflects his God-intoxicated state.',
        teachings: ['Knowledge illumined by devotion', 'Ecstatic God-vision', 'Lakshmi-Narayana worship'],
        works: ['Moondram Tiruvandhadhi (100 verses)'],
        quotes: ['"I saw the Lord with the Goddess, standing before us three."'],
        image: 'pey.jpg'
    },
    {
        id: 'thirumazhisai',
        name: 'Thirumazhisai Alvar',
        nameLocal: 'திருமழிசையாழ்வார்',
        nameHi: 'तिरुमळिसै आळ्वार',
        tradition: 'hindu',
        sampradaya: 'Alvar',
        period: '7th-8th century CE',
        birthPlace: 'Thirumazhisai, Tamil Nadu',
        biography: 'Thirumazhisai Alvar was unique for having explored Shaivism, Buddhism, and Jainism before finding truth in Vaishnavism. His philosophical depth earned him the title "Bhaktisara" (Essence of Devotion). He demonstrated that Narayana is the Supreme through reasoned argument and experience.',
        teachings: ['Vishnu as Supreme through logic', 'Rejection of other paths', 'Philosophical devotion'],
        works: ['Nanmugan Tiruvandhadhi', 'Tiruchanda Viruttam'],
        quotes: ['"After searching all paths, I found peace only in Narayana."'],
        image: 'thirumazhisai.jpg'
    },
    {
        id: 'thondaradippodi',
        name: 'Thondaradippodi Alvar',
        nameLocal: 'தொண்டரடிப்பொடியாழ்வார்',
        nameHi: 'तोंडरडिप्पोडि आळ्वार',
        tradition: 'hindu',
        sampradaya: 'Alvar',
        period: '8th century CE',
        birthPlace: 'Mandangudi, Tamil Nadu',
        biography: 'Thondaradippodi Alvar\'s name means "Dust at the feet of devotees." He served the Srirangam temple by maintaining a garden of tulsi for the Lord. His Tirumaalai is a deeply emotional work expressing longing for Ranganatha. Legend says he was once tempted away but returned with deeper humility.',
        teachings: ['Humility before devotees', 'Tulsi seva', 'Emotional surrender'],
        works: ['Tirumaalai', 'Tirupalliyezhuchi'],
        quotes: ['"I am but the dust beneath the feet of the devotees."'],
        image: 'thondaradippodi.jpg'
    },
    {
        id: 'thiruppaan',
        name: 'Thiruppaan Alvar',
        nameLocal: 'திருப்பாணாழ்வார்',
        nameHi: 'तिरुप्पाण आळ्वार',
        tradition: 'hindu',
        sampradaya: 'Alvar',
        period: '8th century CE',
        birthPlace: 'Uraiyur, Tamil Nadu',
        biography: 'Thiruppaan Alvar was born in the Panar (bard) community, considered untouchable. Though forbidden to enter temples, he stood outside Srirangam singing. One day, Lord Ranganatha commanded the temple priest to carry Thiruppaan inside on his shoulders. His Amalanaadhipiraan describes Vishnu from foot to head in 10 verses.',
        teachings: ['Devotion transcends caste', 'God welcomes all', 'Beauty of divine form'],
        works: ['Amalanaadhipiraan (10 verses)'],
        quotes: ['"My eyes, having seen Ranganatha, shall not see anything else."'],
        image: 'thiruppaan.jpg'
    },
    {
        id: 'madhurakavi',
        name: 'Madhurakavi Alvar',
        nameLocal: 'மதுரகவியாழ்வார்',
        nameHi: 'मधुरकवि आळ्वार',
        tradition: 'hindu',
        sampradaya: 'Alvar',
        period: '7th century CE',
        birthPlace: 'Thirukolur, Tamil Nadu',
        biography: 'Madhurakavi Alvar is unique among Alvars for composing verses not to Vishnu directly, but to his guru Nammalvar. He discovered Nammalvar meditating under a tamarind tree and became his devoted disciple. His 11 verses, Kanninun Siruthambu, express pure devotion to a human guru.',
        teachings: ['Guru bhakti', 'Devotion to a saint as path to God', 'Humility'],
        works: ['Kanninun Siruthambu (11 verses)'],
        quotes: ['"Nammalvar is my God; I know no other."'],
        image: 'madhurakavi.jpg'
    },
    // ========== HINDU - NAYANARS ==========
    {
        id: 'appar',
        name: 'Appar',
        nameLocal: 'அப்பர்',
        nameHi: 'अप्पर',
        tradition: 'hindu',
        sampradaya: 'Nayanar',
        period: '7th century CE',
        birthPlace: 'Tiruvamur, Tamil Nadu',
        biography: 'Thirunavukkarasar, known as Appar, was one of the foremost Nayanar saints. Originally a Jain monk, he converted to Shaivism after a severe illness was cured by invoking Shiva. Despite persecution by the Pallava king (a Jain), he stood firm in his faith. His Tevaram hymns emphasize humble service (cleaning temple grounds) as true devotion.',
        teachings: ['Service to Shiva through temple work', 'Devotion overcomes all suffering', 'True religion is felt in the heart'],
        works: ['Tevaram (4th, 5th, 6th Thirumurais)'],
        quotes: ['"Even if you do not love us, we shall love you, O Lord."'],
        image: 'appar.jpg'
    },
    {
        id: 'sambandar',
        name: 'Thirugnana Sambandar',
        nameLocal: 'திருஞானசம்பந்தர்',
        nameHi: 'तिरुज्ञान संबंदर',
        tradition: 'hindu',
        sampradaya: 'Nayanar',
        period: '7th century CE',
        birthPlace: 'Sirkali, Tamil Nadu',
        biography: 'A child prodigy, Sambandar is said to have been fed divine milk by Goddess Parvati at age three, after which he began composing hymns. He traveled extensively, performing miracles and debating Jain scholars. He is credited with reviving Shaivism in the Pandya kingdom. He composed over 4000 verses of the Tevaram.',
        teachings: ['Shiva as the Supreme Reality', 'Power of Namasivaya mantra', 'Bhakti defeats all philosophies'],
        works: ['Tevaram (1st, 2nd, 3rd Thirumurais)'],
        quotes: ['"Those who chant Namasivaya have nothing to fear."'],
        image: 'sambandar.jpg'
    },
    {
        id: 'sundarar',
        name: 'Sundarar',
        nameLocal: 'சுந்தரர்',
        nameHi: 'सुंदरर',
        tradition: 'hindu',
        sampradaya: 'Nayanar',
        period: '8th century CE',
        birthPlace: 'Tirunavalur, Tamil Nadu',
        biography: 'Sundarar is the third of the Moovar (three chief Nayanars). Unlike other saints who approached Shiva as master or father, Sundarar related to Him as a friend (Sakha). He is famous for the Tiruthonda Thogai, which lists the names of the 63 Nayanars, becoming the basis for the Periya Puranam.',
        teachings: ['Shiva as friend', 'Catalog of saints', 'Emotional devotion'],
        works: ['Tevaram (7th Thirumurai)', 'Tiruthonda Thogai'],
        quotes: ['"O Shiva, my friend, stand by me in my folly."'],
        image: 'sundarar.jpg'
    },
    {
        id: 'manikkavacakar',
        name: 'Manikkavacakar',
        nameLocal: 'மாணிக்கவாசகர்',
        nameHi: 'माणिक्कवाचकर',
        tradition: 'hindu',
        sampradaya: 'Nayanar',
        period: '9th century CE',
        birthPlace: 'Thiruvathavur, Tamil Nadu',
        biography: 'Manikkavacakar was a minister to the Pandya king who renounced everything after a divine encounter with Shiva at Tiruperunturai. His Tiruvasagam is considered the peak of Tamil devotional literature, known for its heart-melting pathos that says "Those whose hearts don\'t melt at Tiruvasagam won\'t melt at anything."',
        teachings: ['Total surrender', 'Grace of Shiva', 'Emotional melting (urugaar)'],
        works: ['Tiruvasagam', 'Tirukkovaiyar'],
        quotes: ['"He who melts not at Tiruvasagam, his heart is made of stone."'],
        image: 'manikkavacakar.jpg'
    },
    {
        id: 'karaikkal',
        name: 'Karaikkal Ammaiyar',
        nameLocal: 'காரைக்கால் அம்மையார்',
        nameHi: 'कारैक्काल अम्मैयार',
        tradition: 'hindu',
        sampradaya: 'Nayanar',
        period: '6th century CE',
        birthPlace: 'Karaikkal, Tamil Nadu',
        biography: 'Karaikkal Ammaiyar is one of the earliest Nayanar saints and one of the few women among them. Originally a beautiful woman named Punitavati, she prayed to Shiva to take away her physical beauty so she could worship him without distraction. Shiva granted her wish, transforming her into a skeletal form. She worshipped Shiva in cremation grounds.',
        teachings: ['Transcending physical beauty', 'Devotion in cremation grounds', 'Complete dedication'],
        works: ['Arputha Thiruvandhadhi', 'Thiruirattai Manimaalai'],
        quotes: ['"I chose divine ugliness over mortal beauty."'],
        image: 'karaikkal.jpg'
    },
    {
        id: 'kannappa',
        name: 'Kannappa Nayanar',
        nameLocal: 'கண்ணப்பர்',
        nameHi: 'कण्णप्पर',
        tradition: 'hindu',
        sampradaya: 'Nayanar',
        period: 'Mythological Era',
        birthPlace: 'Uduppura (Kalahasti), Andhra Pradesh',
        biography: 'Kannappa was a tribal hunter named Thinnan who discovered a Shiva Lingam in the forest. With no knowledge of rituals, he offered meat and water (carried in his mouth). When the Lingam\'s eyes bled, he tried to fix it by gouging out his own eyes. Shiva stopped him, declaring this innocent love supreme devotion.',
        teachings: ['Innocence over ritual', 'True love offering', 'God accepts sincerity'],
        works: ['His story in Periya Puranam'],
        quotes: ['"What use are my eyes if my Lord\'s eyes bleed?"'],
        image: 'kannappa.jpg'
    },
    // ========== HINDU - VARKARI ==========
    {
        id: 'dnyaneshwar',
        name: 'Sant Dnyaneshwar',
        nameLocal: 'संत ज्ञानेश्वर',
        nameHi: 'संत ज्ञानेश्वर',
        tradition: 'hindu',
        sampradaya: 'Varkari',
        period: '1275-1296 CE',
        birthPlace: 'Apegaon, Maharashtra',
        biography: 'Sant Dnyaneshwar (also Jnaneshwar) was a child prodigy who wrote the Dnyaneshwari, a Marathi commentary on the Bhagavad Gita, at age 15. Born to parents who had renounced worldly life and later returned, he faced social ostracism. Despite his short life of 21 years, he democratized Vedantic knowledge by writing in Marathi. He voluntarily entered Sanjivan Samadhi at Alandi.',
        teachings: ['Knowledge and devotion are one', 'Spiritual wisdom for all castes', 'The world is a manifestation of Brahman'],
        works: ['Dnyaneshwari', 'Amrutanubhav', 'Changdev Pasashti', 'Abhangas'],
        quotes: ['"May the universe be blessed with peace and happiness." (Pasaydan)'],
        image: 'dnyaneshwar.jpg'
    },
    {
        id: 'namdev',
        name: 'Sant Namdev',
        nameLocal: 'संत नामदेव',
        nameHi: 'संत नामदेव',
        tradition: 'hindu',
        sampradaya: 'Varkari',
        period: '1270-1350 CE',
        birthPlace: 'Narasi-Bamani, Maharashtra',
        biography: 'Sant Namdev was a tailor (shimpi) by caste who became one of the pillars of the Varkari movement. He traveled across India spreading the message of bhakti, including to Punjab, where his hymns are included in the Guru Granth Sahib. He composed thousands of abhangs and played a key role in democratizing devotion to Vitthal.',
        teachings: ['Name of God is the path', 'Caste is irrelevant in devotion', 'God dwells in every being'],
        works: ['Abhangs', 'Gatha', '61 hymns in Guru Granth Sahib'],
        quotes: ['"Nama says: In the Naam alone is liberation."'],
        image: 'namdev.jpg'
    },
    {
        id: 'tukaram',
        name: 'Sant Tukaram',
        nameLocal: 'संत तुकाराम',
        nameHi: 'संत तुकाराम',
        tradition: 'hindu',
        sampradaya: 'Varkari',
        period: '1608-1650 CE',
        birthPlace: 'Dehu, Maharashtra',
        biography: 'Sant Tukaram was a grocer (Shudra caste) who became the most beloved poet-saint of Maharashtra. After family tragedies, he turned entirely to devotion. His Gatha (collection of 4000+ abhangs) expresses devotion to Vitthal with simple yet profound poetry. He faced persecution from orthodox Brahmins who forced him to throw his manuscripts in the river, but they reportedly floated back.',
        teachings: ['Simple heartfelt devotion', 'Equality before God', 'Renunciation of ego'],
        works: ['Tukaram Gatha (4600+ Abhangs)'],
        quotes: ['"Tuka says, this world is a dream, wake up and turn to God."'],
        image: 'tukaram.jpg'
    },
    {
        id: 'eknath',
        name: 'Sant Eknath',
        nameLocal: 'संत एकनाथ',
        nameHi: 'संत एकनाथ',
        tradition: 'hindu',
        sampradaya: 'Varkari',
        period: '1533-1599 CE',
        birthPlace: 'Paithan, Maharashtra',
        biography: 'Sant Eknath was a Brahmin householder who harmonized spiritual life with worldly duties. He edited and restored the Dnyaneshwari to preserve its authenticity. He wrote the Eknathi Bhagwat, a Marathi rendering of the 11th Skandha of Bhagavata Purana. He was known for serving Dalits and breaking caste barriers.',
        teachings: ['Householder spirituality', 'Preservation of texts', 'Service to all castes'],
        works: ['Eknathi Bhagwat', 'Bhavartha Ramayana', 'Abhangas', 'Bharuds'],
        quotes: ['"God dwells in the heart of the pure, regardless of caste."'],
        image: 'eknath.jpg'
    },
    {
        id: 'chokhamela',
        name: 'Sant Chokhamela',
        nameLocal: 'संत चोखामेळा',
        nameHi: 'संत चोखामेळा',
        tradition: 'hindu',
        sampradaya: 'Varkari',
        period: '14th century CE',
        birthPlace: 'Mehuna, Maharashtra',
        biography: 'Sant Chokhamela was a Mahar (Dalit) saint who questioned the notions of purity and pollution. Though forbidden to enter the Pandharpur temple, he stood outside singing to Vitthal. His abhangs powerfully argue that God belongs to the downtrodden. He died while working on a forced labor project.',
        teachings: ['God belongs to the oppressed', 'Caste is a social sin', 'Inner purity over birth'],
        works: ['Abhangas'],
        quotes: ['"I am impure by birth, but my mind is pure for you, Vitthal."'],
        image: 'chokhamela.jpg'
    },
    {
        id: 'janabai',
        name: 'Sant Janabai',
        nameLocal: 'संत जनाबाई',
        nameHi: 'संत जनाबाई',
        tradition: 'hindu',
        sampradaya: 'Varkari',
        period: '1263-1350 CE',
        birthPlace: 'Gangakhed, Maharashtra',
        biography: 'Sant Janabai was a maidservant in the household of Sant Namdev. Despite her status, she composed over 340 abhangas while grinding grain and doing household chores. Her poetry illustrates that every mundane task can become worship. She claimed that Vitthal himself would help her with her work.',
        teachings: ['Work as worship', 'Devotion in daily chores', 'Women\'s spiritual equality'],
        works: ['Janabai Gatha (340+ Abhangas)'],
        quotes: ['"While I grind, Vitthal turns the stone with me."'],
        image: 'janabai.jpg'
    },
    {
        id: 'samarth',
        name: 'Samarth Ramdas',
        nameLocal: 'समर्थ रामदास',
        nameHi: 'समर्थ रामदास',
        tradition: 'hindu',
        sampradaya: 'Varkari',
        period: '1608-1681 CE',
        birthPlace: 'Jamb, Maharashtra',
        biography: 'Samarth Ramdas was a contemporary of Shivaji Maharaj and his spiritual guide. Unlike other Varkari saints who emphasized gentle devotion, Ramdas combined Bhakti with Shakti (power), inspiring the Maratha empire. He established maths (monasteries) across India and authored the Dasbodh, a comprehensive guide to spiritual and worldly life.',
        teachings: ['Bhakti with Shakti', 'Self-reliance', 'Physical and spiritual strength', 'Service to motherland'],
        works: ['Dasbodh', 'Manache Shlok', 'Karunashtakas'],
        quotes: ['"Jay Jay Raghuveer Samarth!" (Victory to the mighty Rama!)'],
        image: 'samarth.jpg'
    },
    // ========== HINDU - NORTH INDIA ==========
    {
        id: 'ramananda',
        name: 'Swami Ramananda',
        nameLocal: 'स्वामी रामानंद',
        nameHi: 'स्वामी रामानंद',
        tradition: 'hindu',
        sampradaya: 'Nirguna Sant',
        period: '14th-15th century CE',
        birthPlace: 'Prayagraj, Uttar Pradesh',
        biography: 'Swami Ramananda was the pivotal figure who brought the Bhakti movement from South India to the North. He broke caste barriers by accepting disciples from all backgrounds including Kabir (weaver), Ravidas (cobbler), Sena (barber), and Pipa (king). His Ram-bhakti focused on God as the inner self.',
        teachings: ['Bhakti for all castes', 'Rama as inner self', 'Bridge between South and North'],
        works: ['Hindi verses', 'Spiritual commentaries'],
        quotes: ['"Caste and creed have no place in spirituality."'],
        image: 'ramananda.jpg'
    },
    {
        id: 'kabir',
        name: 'Sant Kabir',
        nameLocal: 'कबीर दास',
        nameHi: 'संत कबीर',
        tradition: 'hindu',
        sampradaya: 'Nirguna Sant',
        period: '1398-1518 CE',
        birthPlace: 'Varanasi, Uttar Pradesh',
        biography: 'Kabir was a weaver-mystic whose verses rejected both Hindu and Islamic orthodoxy in favor of direct experience of the formless Divine. Found as a baby on a lotus in a lake, he was raised by Muslim weavers but became a disciple of the Hindu saint Ramananda. His dohas and songs are shared by Hindus, Sikhs, and Muslims alike.',
        teachings: ['God is formless (Nirguna)', 'Inner experience over ritual', 'Both Hindu and Muslim paths lead to one God'],
        works: ['Bijak', 'Kabir Granthavali', 'Dohas/Sakhis', 'Hymns in Guru Granth Sahib'],
        quotes: ['"Kabir says: Seek within; you carry the entire universe in you."'],
        image: 'kabir.jpg'
    },
    {
        id: 'ravidas',
        name: 'Sant Ravidas',
        nameLocal: 'गुरु रविदास',
        nameHi: 'संत रविदास',
        tradition: 'hindu',
        sampradaya: 'Nirguna Sant',
        period: '15th-16th century CE',
        birthPlace: 'Varanasi, Uttar Pradesh',
        biography: 'Sant Ravidas (Raidas) was a cobbler by caste who became one of the most influential saints of North India. A disciple of Ramananda, he taught that caste discrimination has no place in spirituality. He envisioned "Begumpura" – a city without sorrow where all are equal. His 41 hymns are included in the Guru Granth Sahib.',
        teachings: ['Spiritual equality', 'Begumpura - casteless utopia', 'Devotion purifies the soul'],
        works: ['Ravidasi Bani', '41 hymns in Guru Granth Sahib'],
        quotes: ['"If the Creator dwells in all, why discriminate?"'],
        image: 'ravidas.jpg'
    },
    {
        id: 'tulsidas',
        name: 'Goswami Tulsidas',
        nameLocal: 'तुलसीदास',
        nameHi: 'गोस्वामी तुलसीदास',
        tradition: 'hindu',
        sampradaya: 'Saguna Bhakti',
        period: '1532-1623 CE',
        birthPlace: 'Rajapur, Uttar Pradesh',
        biography: 'Tulsidas is the author of the Ramcharitmanas, the retelling of the Ramayana in Awadhi that became the defining text of North Indian Hinduism. Abandoned at birth and raised by a sadhu, he later became obsessed with his wife, then redirected that love to Lord Rama. His works made the story of Rama accessible to common people.',
        teachings: ['Rama as Supreme Lord', 'Devotion through story', 'Dharma in daily life'],
        works: ['Ramcharitmanas', 'Hanuman Chalisa', 'Vinaya Patrika', 'Kavitavali'],
        quotes: ['"As the fragrance is in the flower, so is God in the creation."'],
        image: 'tulsidas.jpg'
    },
    {
        id: 'meera',
        name: 'Meera Bai',
        nameLocal: 'मीराबाई',
        nameHi: 'मीराबाई',
        tradition: 'hindu',
        sampradaya: 'Saguna Bhakti',
        period: '1498-1546 CE',
        birthPlace: 'Kudki, Rajasthan',
        biography: 'Meera Bai was a Rajput princess who devoted her life entirely to Lord Krishna, whom she considered her true husband. Despite persecution by her royal in-laws (including poison attempts), she continued to sing and dance in temples. She eventually left the palace to wander as a bhakti saint, composing devotional songs that remain popular today.',
        teachings: ['Divine love (Prem Bhakti)', 'Krishna as eternal beloved', 'Renunciation of worldly ties'],
        works: ['Bhajans and Padas'],
        quotes: ['"Mira is dyed in the color of Krishna."'],
        image: 'meera.jpg'
    },
    {
        id: 'chaitanya',
        name: 'Chaitanya Mahaprabhu',
        nameLocal: 'চৈতন্য মহাপ্রভু',
        nameHi: 'चैतन्य महाप्रभु',
        tradition: 'hindu',
        sampradaya: 'Gaudiya Vaishnavism',
        period: '1486-1534 CE',
        birthPlace: 'Nabadwip, Bengal',
        biography: 'Chaitanya Mahaprabhu founded Gaudiya Vaishnavism and popularized the public chanting of Hare Krishna (Sankirtan). Originally a scholar named Vishvambhar, he underwent a spiritual transformation and became an ecstatic devotee. He is considered by his followers to be an avatar of Krishna and Radha combined.',
        teachings: ['Sankirtan (congregational chanting)', 'Radha-Krishna devotion', 'Acintya Bheda Abheda philosophy'],
        works: ['Siksastakam (8 verses)'],
        quotes: ['"Chant the names of the Lord and your life will be blessed."'],
        image: 'chaitanya.jpg'
    },
    {
        id: 'surdas',
        name: 'Surdas',
        nameLocal: 'सूरदास',
        nameHi: 'सूरदास',
        tradition: 'hindu',
        sampradaya: 'Pushtimarga',
        period: '1478-1583 CE',
        birthPlace: 'Sihi, Haryana',
        biography: 'Surdas was a blind poet-saint whose Sur Sagar (Ocean of Sur) contains over 100,000 verses describing the childhood and youth of Krishna. Despite (or because of) his blindness, his poetry is extraordinarily visual, capturing every detail of Krishna\'s lilas in Vrindavan. He was a disciple of Vallabhacharya and one of the Ashtachap poets.',
        teachings: ['Krishna\'s childhood lilas', 'Pushti Marga (grace path)', 'Visual poetry despite blindness'],
        works: ['Sur Sagar', 'Sur Saravali', 'Sahitya Lahiri'],
        quotes: ['"The eyes that see not Krishna have seen nothing at all."'],
        image: 'surdas.jpg'
    },
    {
        id: 'narsinh',
        name: 'Narsinh Mehta',
        nameLocal: 'નરસિંહ મહેતા',
        nameHi: 'नरसिंह मेहता',
        tradition: 'hindu',
        sampradaya: 'Saguna Bhakti',
        period: '15th century CE',
        birthPlace: 'Talaja, Gujarat',
        biography: 'Narsinh Mehta is revered as the Adi Kavi (first poet) of Gujarati literature. His bhajan "Vaishnav Jan To" became the defining moral compass of modern India through Mahatma Gandhi, who made it his favorite prayer. Despite facing poverty and social ostracism, he composed hundreds of devotional songs to Krishna.',
        teachings: ['True Vaishnava is one who feels others\' pain', 'Devotion over caste', 'Krishna bhakti'],
        works: ['Vaishnav Jan To', 'Prabhatiya', 'Madhusudano Mari Naiya'],
        quotes: ['"He is a true Vaishnava who feels the pain of others."'],
        image: 'narsinh.jpg'
    },
    // ========== HINDU - SOUTH INDIA HARIDASA ==========
    {
        id: 'purandaradasa',
        name: 'Purandara Dasa',
        nameLocal: 'ಪುರಂದರದಾಸ',
        nameHi: 'पुरंदर दास',
        tradition: 'hindu',
        sampradaya: 'Haridasa',
        period: '1484-1564 CE',
        birthPlace: 'Purandarapur, Karnataka',
        biography: 'Purandara Dasa is revered as the "Pitamaha" (grandfather) of Carnatic music. Originally a wealthy merchant, he renounced everything after a divine transformation. He systematized the teaching of Carnatic music and composed 475,000 songs (of which 1000 survive). Every student of Carnatic music begins with his compositions.',
        teachings: ['Music as devotion', 'Systematic learning of arts', 'Renunciation of wealth'],
        works: ['Carnatic kritis', 'Keerthanas', 'Sarali Varisai method'],
        quotes: ['"Jagadodharana, adisidale Yashoda - The protector of the world is rocked by Yashoda."'],
        image: 'purandaradasa.jpg'
    },
    {
        id: 'kanakadasa',
        name: 'Kanaka Dasa',
        nameLocal: 'ಕನಕದಾಸ',
        nameHi: 'कनक दास',
        tradition: 'hindu',
        sampradaya: 'Haridasa',
        period: '1509-1609 CE',
        birthPlace: 'Bada, Karnataka',
        biography: 'Kanaka Dasa was a shepherd (Kuruba) by caste who became one of the greatest Haridasa poets. When denied entry to the Udupi Krishna temple due to caste, he stood at the back – legend says the idol turned around to face him through a window (now called Kanakana Kindi). He composed philosophical and devotional works that questioned caste hierarchy.',
        teachings: ['God sees devotion, not caste', 'Social equality', 'Krishna devotion'],
        works: ['Nalacharitre', 'Mohanatarangini', 'Ramadhanya Charite', 'Keerthanas'],
        quotes: ['"What is the caste of the soul? Tell me, O pundit!"'],
        image: 'kanakadasa.jpg'
    },
    {
        id: 'vyasatirtha',
        name: 'Vyasatirtha',
        nameLocal: 'ವ್ಯಾಸತೀರ್ಥ',
        nameHi: 'व्यासतीर्थ',
        tradition: 'hindu',
        sampradaya: 'Haridasa',
        period: '1460-1539 CE',
        birthPlace: 'Bannur, Karnataka',
        biography: 'Vyasatirtha (Vyasaraya) was the Rajaguru of the Vijayanagara Empire and a pivotal figure in the Haridasa movement. He patronized both Purandara Dasa and Kanaka Dasa, bridging the caste divide. He was the pontiff of the Madhva order and established numerous Krishna temples.',
        teachings: ['Dvaita Vedanta', 'Patronage of arts', 'Unity across castes'],
        works: ['Nyayamruta', 'Tarkatandava', 'Chandrika'],
        quotes: ['"Devotion knows no boundary of birth or caste."'],
        image: 'vyasatirtha.jpg'
    },
    {
        id: 'raghavendra',
        name: 'Raghavendra Swami',
        nameLocal: 'ರಾಘವೇಂದ್ರ ಸ್ವಾಮಿ',
        nameHi: 'राघवेंद्र स्वामी',
        tradition: 'hindu',
        sampradaya: 'Haridasa',
        period: '1595-1671 CE',
        birthPlace: 'Bhuvanagiri, Tamil Nadu',
        biography: 'Raghavendra Swami was a Madhva saint known for his miracles and deep scholarship. He entered Brindavana (live burial in meditation) at Mantralaya, where his tomb remains a major pilgrimage site today. Thousands visit daily believing he still answers prayers from his Samadhi.',
        teachings: ['Madhva philosophy', 'Miracles of faith', 'Service to devotees'],
        works: ['Commentaries on Vedanta', 'Parimala'],
        quotes: ['"I will continue to serve devotees from my Brindavana for 700 years."'],
        image: 'raghavendra.jpg'
    },
    // ========== SIKH GURUS ==========
    {
        id: 'gurunanak',
        name: 'Guru Nanak Dev Ji',
        nameLocal: 'ਗੁਰੂ ਨਾਨਕ ਦੇਵ ਜੀ',
        nameHi: 'गुरु नानक देव जी',
        tradition: 'sikh',
        sampradaya: 'Gurus',
        period: '1469-1539 CE',
        birthPlace: 'Talwandi (Nankana Sahib), Punjab',
        biography: 'Guru Nanak Dev Ji is the founder of Sikhism and the first of the Ten Gurus. After a divine experience at age 30, he traveled extensively (Udasis) across South Asia and the Middle East, teaching "There is no Hindu, there is no Muslim" – only seekers of Truth. He established the principles of Ik Onkar (One God), Naam Japna, Kirat Karni, and Vand Chakna.',
        teachings: ['Ik Onkar - One God', 'Equality of all humans', 'Honest living and sharing', 'Naam Simran (remembrance of God)'],
        works: ['Japji Sahib', 'Asa di Var', 'Sidh Gosht', 'Babar Vani'],
        quotes: ['"Truth is the highest virtue, but higher still is truthful living."'],
        image: 'gurunanak.jpg'
    },
    {
        id: 'guruangad',
        name: 'Guru Angad Dev Ji',
        nameLocal: 'ਗੁਰੂ ਅੰਗਦ ਦੇਵ ਜੀ',
        nameHi: 'गुरु अंगद देव जी',
        tradition: 'sikh',
        sampradaya: 'Gurus',
        period: '1504-1552 CE',
        birthPlace: 'Harike, Punjab',
        biography: 'Guru Angad Dev Ji was the second Sikh Guru. Originally named Lehna, he became Guru Nanak\'s closest disciple and successor. He standardized and promoted the Gurmukhi script, making the Guru\'s teachings accessible. He also promoted physical fitness (Mal Akhara) and expanded the Langar tradition.',
        teachings: ['Promotion of Gurmukhi script', 'Physical and spiritual discipline', 'Continuation of Langar'],
        works: ['63 Saloks in Guru Granth Sahib'],
        quotes: ['"If you want to play the game of love, come with your head on your palm."'],
        image: 'guruangad.jpg'
    },
    {
        id: 'guruamardas',
        name: 'Guru Amar Das Ji',
        nameLocal: 'ਗੁਰੂ ਅਮਰ ਦਾਸ ਜੀ',
        nameHi: 'गुरु अमर दास जी',
        tradition: 'sikh',
        sampradaya: 'Gurus',
        period: '1479-1574 CE',
        birthPlace: 'Basarke Gillan, Punjab',
        biography: 'Guru Amar Das Ji became the third Guru at age 73. He institutionalized the Langar, requiring even Emperor Akbar to sit on the floor to eat with commoners. He strongly opposed Sati and purdah, and established the Manji system for spreading Sikh teachings. He constructed the Baoli at Goindval.',
        teachings: ['Institutionalized Langar', 'Women\'s equality', 'Opposition to Sati', 'Manji administration system'],
        works: ['Anand Sahib', 'Hymns in Guru Granth Sahib'],
        quotes: ['"True are the words of the Guru; Blessed is the heart that knows this."'],
        image: 'guruamardas.jpg'
    },
    {
        id: 'gururamdas',
        name: 'Guru Ram Das Ji',
        nameLocal: 'ਗੁਰੂ ਰਾਮ ਦਾਸ ਜੀ',
        nameHi: 'गुरु राम दास जी',
        tradition: 'sikh',
        sampradaya: 'Gurus',
        period: '1534-1581 CE',
        birthPlace: 'Lahore, Punjab',
        biography: 'Guru Ram Das Ji was the fourth Guru and founder of Amritsar (city of nectar). He excavated the sacred pool (Amrit Sarovar) that would later become the site of the Harmandir Sahib. He composed the Lavan, the hymn used in Sikh marriage ceremonies.',
        teachings: ['Foundation of Amritsar', 'Lavan for Anand Karaj', 'Humility and service'],
        works: ['Lavan', 'Hymns in Guru Granth Sahib'],
        quotes: ['"The Guru is the boat to cross the ocean of darkness."'],
        image: 'gururamdas.jpg'
    },
    {
        id: 'guruarjan',
        name: 'Guru Arjan Dev Ji',
        nameLocal: 'ਗੁਰੂ ਅਰਜਨ ਦੇਵ ਜੀ',
        nameHi: 'गुरु अर्जन देव जी',
        tradition: 'sikh',
        sampradaya: 'Gurus',
        period: '1563-1606 CE',
        birthPlace: 'Goindval, Punjab',
        biography: 'Guru Arjan Dev Ji was the fifth Guru and the first Sikh martyr. He compiled the Adi Granth (first edition of Guru Granth Sahib), completed the Harmandir Sahib, and composed the most hymns of any Gurus. He was tortured and executed by Mughal Emperor Jahangir for refusing to convert.',
        teachings: ['Compilation of Adi Granth', 'Completion of Harmandir Sahib', 'Martyrdom for faith'],
        works: ['2218 hymns in Guru Granth Sahib', 'Sukhmani Sahib'],
        quotes: ['"Sweet is Your will, O Lord; I ask only for the gift of Your Name."'],
        image: 'guruarjan.jpg'
    },
    {
        id: 'guruhargobind',
        name: 'Guru Hargobind Ji',
        nameLocal: 'ਗੁਰੂ ਹਰਿਗੋਬਿੰਦ ਜੀ',
        nameHi: 'गुरु हरगोबिंद जी',
        tradition: 'sikh',
        sampradaya: 'Gurus',
        period: '1595-1644 CE',
        birthPlace: 'Guru Ki Wadali, Punjab',
        biography: 'Guru Hargobind Ji was the sixth Guru and introduced the concept of Miri-Piri (temporal and spiritual authority). He wore two swords representing these dual powers. After his father\'s martyrdom, he militarized the Sikhs, built the Akal Takht, and fought several battles against Mughal forces.',
        teachings: ['Miri-Piri concept', 'Self-defense as dharma', 'Akal Takht establishment'],
        works: ['Oral teachings'],
        quotes: ['"Arms are necessary for the defense of righteousness."'],
        image: 'guruhargobind.jpg'
    },
    {
        id: 'guruharrai',
        name: 'Guru Har Rai Ji',
        nameLocal: 'ਗੁਰੂ ਹਰਿ ਰਾਇ ਜੀ',
        nameHi: 'गुरु हर राय जी',
        tradition: 'sikh',
        sampradaya: 'Gurus',
        period: '1630-1661 CE',
        birthPlace: 'Kiratpur Sahib, Punjab',
        biography: 'Guru Har Rai Ji was the seventh Guru, known for his gentle nature and love for nature. He maintained an army but prioritized peace. He established a dispensary of Ayurvedic medicines and once reportedly healed Dara Shikoh, son of Shah Jahan.',
        teachings: ['Compassion for all beings', 'Herbal medicine', 'Maintenance of peace'],
        works: ['Oral teachings'],
        quotes: ['"A broken heart can be bound, but a trampled flower never blooms again."'],
        image: 'guruharrai.jpg'
    },
    {
        id: 'guruharkrishan',
        name: 'Guru Har Krishan Ji',
        nameLocal: 'ਗੁਰੂ ਹਰਿ ਕ੍ਰਿਸ਼ਨ ਜੀ',
        nameHi: 'गुरु हर कृष्ण जी',
        tradition: 'sikh',
        sampradaya: 'Gurus',
        period: '1656-1664 CE',
        birthPlace: 'Kiratpur Sahib, Punjab',
        biography: 'Guru Har Krishan Ji was the eighth Guru and the youngest (became Guru at age 5). Called the "Child Guru," he served victims during a smallpox epidemic in Delhi, contracting the disease himself. Before passing at age 8, he indicated his successor with "Baba Bakale" (referring to Guru Tegh Bahadur).',
        teachings: ['Service to the suffering', 'Divine wisdom transcends age'],
        works: ['Oral teachings'],
        quotes: ['"Blessed is the one who loses himself in service."'],
        image: 'guruharkrishan.jpg'
    },
    {
        id: 'guruteghbahadur',
        name: 'Guru Tegh Bahadur Ji',
        nameLocal: 'ਗੁਰੂ ਤੇਗ ਬਹਾਦਰ ਜੀ',
        nameHi: 'गुरु तेग बहादुर जी',
        tradition: 'sikh',
        sampradaya: 'Gurus',
        period: '1621-1675 CE',
        birthPlace: 'Amritsar, Punjab',
        biography: 'Guru Tegh Bahadur Ji was the ninth Guru and second Sikh martyr. Known as "Hind Di Chadar" (Shield of India), he sacrificed his life to protect the religious freedom of Kashmiri Pandits threatened with forced conversion by Aurangzeb. He was executed in Delhi after refusing to convert to Islam or perform miracles.',
        teachings: ['Religious freedom for all', 'Fearlessness', 'Protection of the oppressed'],
        works: ['115 hymns in Guru Granth Sahib', 'Saloks'],
        quotes: ['"He who grieves not, nor is elated, who regards gold and dust alike..."'],
        image: 'guruteghbahadur.jpg'
    },
    {
        id: 'gurugobindsingh',
        name: 'Guru Gobind Singh Ji',
        nameLocal: 'ਗੁਰੂ ਗੋਬਿੰਦ ਸਿੰਘ ਜੀ',
        nameHi: 'गुरु गोबिंद सिंह जी',
        tradition: 'sikh',
        sampradaya: 'Gurus',
        period: '1666-1708 CE',
        birthPlace: 'Patna, Bihar',
        biography: 'Guru Gobind Singh Ji was the tenth and last human Guru of Sikhism. In 1699, he established the Khalsa Panth on Baisakhi, initiated the Five Ks, and created Sant-Sipahi (saint-soldier) identity. He fought against Aurangzeb\'s tyranny, losing his father and four sons. Before passing, he declared the Guru Granth Sahib as the eternal Guru.',
        teachings: ['Creation of Khalsa', 'Five Ks (Kakars)', 'Granth Sahib as eternal Guru', 'Sant-Sipahi concept'],
        works: ['Dasam Granth', 'Jap Sahib', 'Zafarnama'],
        quotes: ['"When all other means have failed, it is righteous to draw the sword."'],
        image: 'gurugobindsingh.jpg'
    },
    // ========== SIKH BHAGATS ==========
    {
        id: 'babafarid',
        name: 'Baba Farid',
        nameLocal: 'ਬਾਬਾ ਫਰੀਦ',
        nameHi: 'बाबा फरीद',
        tradition: 'sikh',
        sampradaya: 'Bhagats',
        period: '1173-1266 CE',
        birthPlace: 'Kothewal, Punjab',
        biography: 'Sheikh Fariduddin Ganjshakar, known as Baba Farid, was a Sufi saint whose 134 hymns are included in the Guru Granth Sahib. He was the first major poet of the Punjabi language. His emphasis on love, humility, and devotion influenced both Sikh and Sufi traditions. He was part of the Chishti Sufi order.',
        teachings: ['Divine love', 'Humility', 'Detachment from worldly desires'],
        works: ['Shaloks in Guru Granth Sahib'],
        quotes: ['"Do not be angry with anyone; look within your own soul."'],
        image: 'babafarid.jpg'
    },
    {
        id: 'bhagattrilochan',
        name: 'Bhagat Trilochan',
        nameLocal: 'ਭਗਤ ਤ੍ਰਿਲੋਚਨ',
        nameHi: 'भगत त्रिलोचन',
        tradition: 'sikh',
        sampradaya: 'Bhagats',
        period: '13th century CE',
        birthPlace: 'Maharashtra',
        biography: 'Bhagat Trilochan was a Vaishya saint from Maharashtra whose four hymns are included in the Guru Granth Sahib. He was a contemporary of Sant Namdev. His compositions emphasize that one\'s last thoughts before death determine their next life, urging constant remembrance of God.',
        teachings: ['Remembrance of God at death', 'Naam Simran', 'Detachment from maya'],
        works: ['4 hymns in Guru Granth Sahib'],
        quotes: ['"At the time of death, whatever you think of, that you become."'],
        image: 'trilochan.jpg'
    },
    {
        id: 'bhagatpipa',
        name: 'Bhagat Pipa',
        nameLocal: 'ਭਗਤ ਪੀਪਾ',
        nameHi: 'भगत पीपा',
        tradition: 'sikh',
        sampradaya: 'Bhagats',
        period: '14th-15th century CE',
        birthPlace: 'Gagaraungarh, Rajasthan',
        biography: 'Bhagat Pipa was a Rajput king who renounced his throne to become a disciple of Ramananda. His one hymn in the Guru Granth Sahib expresses the discovery of God within oneself. He is remembered for giving up royal power for spiritual pursuit.',
        teachings: ['God dwells within', 'Renunciation of power', 'Inner realization'],
        works: ['1 hymn in Guru Granth Sahib'],
        quotes: ['"Within the body, within the mind, within the soul - I found the Lord."'],
        image: 'pipa.jpg'
    },
    {
        id: 'bhagatdhanna',
        name: 'Bhagat Dhanna',
        nameLocal: 'ਭਗਤ ਧੰਨਾ',
        nameHi: 'भगत धन्ना',
        tradition: 'sikh',
        sampradaya: 'Bhagats',
        period: '15th century CE',
        birthPlace: 'Dhuan, Rajasthan',
        biography: 'Bhagat Dhanna was a Jat farmer whose simple, innocent devotion is celebrated in his hymns in the Guru Granth Sahib. Legend says he worshipped a stone given by a Brahmin with such sincerity that God appeared before him. His poetry reflects the devotion of an unlettered farmer.',
        teachings: ['Simple sincere devotion', 'God responds to innocence', 'Faith of the unlearned'],
        works: ['4 hymns in Guru Granth Sahib'],
        quotes: ['"O Lord, I am just a simple farmer - please accept my humble devotion."'],
        image: 'dhanna.jpg'
    },
    {
        id: 'bhagatsain',
        name: 'Bhagat Sain',
        nameLocal: 'ਭਗਤ ਸੈਣ',
        nameHi: 'भगत सैण',
        tradition: 'sikh',
        sampradaya: 'Bhagats',
        period: '15th century CE',
        birthPlace: 'Rewa, Madhya Pradesh',
        biography: 'Bhagat Sain was a barber by profession who served at the court of Raja Ram of Rewa. Despite his low social status, his devotion was so great that the Lord himself is said to have taken his form to serve the king while Sain was in meditation. His one hymn is included in the Guru Granth Sahib.',
        teachings: ['Devotion transcends profession', 'Service and meditation', 'God protects devotees'],
        works: ['1 hymn in Guru Granth Sahib'],
        quotes: ['"The Lord Himself became my servant when I lost myself in His Name."'],
        image: 'sain.jpg'
    },
    {
        id: 'bhagatjaidev',
        name: 'Bhagat Jaidev',
        nameLocal: 'ਭਗਤ ਜੈਦੇਵ',
        nameHi: 'भगत जयदेव',
        tradition: 'sikh',
        sampradaya: 'Bhagats',
        period: '12th century CE',
        birthPlace: 'Kindubilva, Bengal',
        biography: 'Bhagat Jaidev was the author of the famous Gita Govinda and court poet of the Sena dynasty. Two of his compositions are included in the Guru Granth Sahib. His poetry describes the divine love between Radha and Krishna and the soul\'s longing for union with God.',
        teachings: ['Divine love poetry', 'Radha-Krishna devotion', 'Soul\'s longing for God'],
        works: ['Gita Govinda', '2 hymns in Guru Granth Sahib'],
        quotes: ['"The Lord is the ocean of compassion, the remover of all suffering."'],
        image: 'jaidev.jpg'
    },
    {
        id: 'bhagatbhikhan',
        name: 'Bhagat Bhikhan',
        nameLocal: 'ਭਗਤ ਭੀਖਨ',
        nameHi: 'भगत भीखन',
        tradition: 'sikh',
        sampradaya: 'Bhagats',
        period: '15th-16th century CE',
        birthPlace: 'Lucknow, Uttar Pradesh',
        biography: 'Bhagat Bhikhan was a Muslim Sufi saint whose two hymns are included in the Guru Granth Sahib. His poetry emphasizes that true devotion requires inner transformation and that God is found through love, not mere ritual.',
        teachings: ['Inner transformation', 'Love over ritual', 'Unity of God'],
        works: ['2 hymns in Guru Granth Sahib'],
        quotes: ['"What use is pilgrimage if the heart remains impure?"'],
        image: 'bhikhan.jpg'
    },
    // ========== JAIN TIRTHANKARAS ==========
    {
        id: 'ajitanatha',
        name: 'Ajitanatha',
        nameLocal: 'अजितनाथ',
        nameHi: 'अजितनाथ',
        tradition: 'jain',
        sampradaya: 'Tirthankara',
        period: 'Mythological Era',
        birthPlace: 'Ayodhya',
        biography: 'Ajitanatha is the second Tirthankara of the current cosmic cycle. Like all Tirthankaras, he was born as a prince and achieved liberation through renunciation and meditation. His symbol is the elephant, and he is associated with the quality of invincibility (Ajita means unconquered).',
        teachings: ['Invincibility through non-attachment', 'Path to liberation', 'Renunciation'],
        works: ['Oral teachings'],
        quotes: ['"True victory is over oneself, not over others."'],
        image: 'ajitanatha.jpg'
    },
    {
        id: 'rishabhanatha',
        name: 'Rishabhanatha',
        nameLocal: 'ऋषभनाथ',
        nameHi: 'ऋषभनाथ (आदिनाथ)',
        tradition: 'jain',
        sampradaya: 'Tirthankara',
        period: 'Mythological Era',
        birthPlace: 'Ayodhya',
        biography: 'Rishabhanatha (also called Adinatha) is the first Tirthankara of the current cosmic cycle (Avasarpini) in Jainism. According to Jain tradition, he taught humanity the arts of civilization including agriculture, cooking, writing, and crafts. He renounced his kingdom and attained Kevala Jnana after rigorous meditation.',
        teachings: ['Ahimsa (non-violence)', 'Aparigraha (non-attachment)', 'Arts of civilization'],
        works: ['Oral teachings'],
        quotes: ['"Non-violence is the highest dharma."'],
        image: 'rishabhanatha.jpg'
    },
    {
        id: 'parshvanatha',
        name: 'Parshvanatha',
        nameLocal: 'पार्श्वनाथ',
        nameHi: 'पार्श्वनाथ',
        tradition: 'jain',
        sampradaya: 'Tirthankara',
        period: '8th century BCE',
        birthPlace: 'Varanasi',
        biography: 'Parshvanatha is the 23rd Tirthankara and the earliest historically attested figure in Jainism. Born as a prince, he renounced his throne at age 30 and attained Kevala Jnana after 83 days of meditation. He established the four-fold vows (Chaturyama) that became the foundation of Jain monastic practice.',
        teachings: ['Four vows (Chaturyama)', 'Non-violence', 'Truthfulness', 'Non-stealing', 'Non-attachment'],
        works: ['Oral teachings'],
        quotes: ['"Kill not any living being."'],
        image: 'parshvanatha.jpg'
    },
    {
        id: 'neminatha',
        name: 'Neminatha',
        nameLocal: 'नेमिनाथ',
        nameHi: 'नेमिनाथ',
        tradition: 'jain',
        sampradaya: 'Tirthankara',
        period: 'Mythological Era',
        birthPlace: 'Shauripur (Mathura region)',
        biography: 'Neminatha is the 22nd Tirthankara and is said to be the cousin of Lord Krishna. On his wedding day, he saw animals being slaughtered for the feast and was so moved by compassion that he renounced the world immediately. Mount Girnar in Gujarat is associated with his liberation. He represents the connection between Jain and Hindu traditions.',
        teachings: ['Compassion for all living beings', 'Renunciation at the height of worldly pleasure', 'Ahimsa'],
        works: ['Oral teachings'],
        quotes: ['"Hearing the cries of animals, I could not marry; I chose liberation instead."'],
        image: 'neminatha.jpg'
    },
    {
        id: 'mahavira',
        name: 'Mahavira',
        nameLocal: 'महावीर',
        nameHi: 'भगवान महावीर',
        tradition: 'jain',
        sampradaya: 'Tirthankara',
        period: '599-527 BCE',
        birthPlace: 'Vaishali (modern Bihar)',
        biography: 'Mahavira (Vardhamana) is the 24th and last Tirthankara of the current cosmic cycle. Born as a prince, he renounced worldly life at age 30 and practiced extreme austerities for 12 years before attaining Kevala Jnana. He reorganized the Jain Sangha and added the fifth vow of celibacy (brahmacharya) to the existing four.',
        teachings: ['Five vows (Pancha Mahavratas)', 'Anekantavada (many-sidedness)', 'Syadvada (conditional assertion)', 'Ahimsa as supreme dharma'],
        works: ['Oral teachings compiled as Agamas'],
        quotes: ['"Do not injure, abuse, oppress, enslave, insult, torment, torture, or kill any living being."'],
        image: 'mahavira.jpg'
    },
    {
        id: 'kundakunda',
        name: 'Acharya Kundakunda',
        nameLocal: 'कुंदकुंद',
        nameHi: 'आचार्य कुंदकुंद',
        tradition: 'jain',
        sampradaya: 'Digambara Acharya',
        period: '2nd century CE',
        birthPlace: 'South India',
        biography: 'Acharya Kundakunda is one of the most revered Digambara Jain acharyas. His works form the doctrinal foundation of Digambara philosophy. The Samayasara (Essence of the Self) is considered his masterpiece, expounding the distinction between the self and non-self from a Nishchaya (ultimate) perspective.',
        teachings: ['Distinction of self and non-self', 'Nishchaya and Vyavahara viewpoints', 'Soul\'s inherent purity'],
        works: ['Samayasara', 'Pravachanasara', 'Niyamasara', 'Pancastikaya'],
        quotes: ['"The soul is its own friend and its own enemy."'],
        image: 'kundakunda.jpg'
    },
    {
        id: 'hemachandra',
        name: 'Acharya Hemachandra',
        nameLocal: 'हेमचंद्र',
        nameHi: 'आचार्य हेमचंद्र',
        tradition: 'jain',
        sampradaya: 'Shvetambara Acharya',
        period: '1089-1172 CE',
        birthPlace: 'Dhandhuka, Gujarat',
        biography: 'Acharya Hemachandra was a Jain scholar, poet, and polymath called "Kalikalasarvajna" (omniscient of the Kali age). He served as advisor to the Solanki kings of Gujarat. He authored works on grammar, philosophy, yoga, and history. His Trishashti-Shalaka-Purusha-Charitra is a major Jain universal history.',
        teachings: ['Integration of knowledge', 'Yoga and meditation', 'Universal history'],
        works: ['Yogashastra', 'Trishashti-Shalaka-Purusha-Charitra', 'Siddha-Hema-Shabdanushasana', 'Dvatrimshatika'],
        quotes: ['"Knowledge without proper conduct is like a lamp without oil."'],
        image: 'hemachandra.jpg'
    },
    // ========== BUDDHIST MASTERS ==========
    {
        id: 'buddha',
        name: 'Gautama Buddha',
        nameLocal: 'गौतम बुद्ध',
        nameHi: 'भगवान बुद्ध',
        tradition: 'buddhist',
        sampradaya: 'Founder',
        period: '563-483 BCE',
        birthPlace: 'Lumbini, Nepal',
        biography: 'Siddhartha Gautama, known as the Buddha (The Awakened One), is revered in Hinduism as the 9th avatar of Lord Vishnu. Born a prince, he renounced worldly life after witnessing suffering. After years of ascetic practice, he attained enlightenment under the Bodhi tree at Bodh Gaya. His teachings of the Four Noble Truths and the Eightfold Path have influenced billions.',
        teachings: ['Four Noble Truths', 'Noble Eightfold Path', 'Middle Way', 'Ahimsa and Compassion'],
        works: ['Dhammapada', 'Suttas (oral teachings)'],
        quotes: ['"Peace comes from within. Do not seek it without."', '"Three things cannot be hidden: the sun, the moon, and the truth."'],
        image: 'buddha.jpg'
    },
    {
        id: 'bodhidharma',
        name: 'Bodhidharma',
        nameLocal: 'बोधिधर्म',
        nameHi: 'बोधिधर्म',
        tradition: 'buddhist',
        sampradaya: 'Zen/Chan',
        period: '5th-6th century CE',
        birthPlace: 'Kanchipuram, South India',
        biography: 'Bodhidharma was an Indian Buddhist monk who traveled to China and founded Zen (Chan) Buddhism. A prince who became a monk, he is credited with bringing meditation practices to the Shaolin Temple and is considered the patriarch of Zen Buddhism. Legend says he meditated facing a wall for nine years.',
        teachings: ['Direct pointing to the mind', 'Meditation as path to enlightenment', 'Zazen practice'],
        works: ['Two Entrances and Four Practices', 'Bloodstream Sermon'],
        quotes: ['"Not thinking about anything is Zen."', '"To find Buddha, all you have to do is see your own nature."'],
        image: 'bodhidharma.jpg'
    },
    {
        id: 'nagarjuna',
        name: 'Acharya Nagarjuna',
        nameLocal: 'नागार्जुन',
        nameHi: 'आचार्य नागार्जुन',
        tradition: 'buddhist',
        sampradaya: 'Madhyamaka',
        period: '150-250 CE',
        birthPlace: 'Vidarbha, South India',
        biography: 'Nagarjuna was one of the most influential Buddhist philosophers, founder of the Madhyamaka (Middle Way) school. A scholar at Nalanda University, his philosophy of Shunyata (emptiness) and the Two Truths doctrine became foundational to Mahayana Buddhism. The Dalai Lama considers him one of the 17 Nalanda Masters.',
        teachings: ['Shunyata (Emptiness)', 'Two Truths doctrine', 'Dependent origination'],
        works: ['Mulamadhyamakakarika', 'Suhrllekha', 'Vigrahavyavartani'],
        quotes: ['"Whatever is dependently arisen is explained to be emptiness."'],
        image: 'nagarjuna.jpg'
    },
    {
        id: 'padmasambhava',
        name: 'Padmasambhava',
        nameLocal: 'पद्मसम्भव',
        nameHi: 'गुरु रिनपोचे',
        tradition: 'buddhist',
        sampradaya: 'Vajrayana',
        period: '8th century CE',
        birthPlace: 'Oddiyana (Swat Valley)',
        biography: 'Padmasambhava, known as Guru Rinpoche (Precious Master), is credited with bringing Vajrayana Buddhism to Tibet. Called the "Second Buddha" in Tibetan Buddhism, he subdued local deities and established the first Buddhist monastery in Tibet. He is said to have hidden treasure texts (termas) for future generations.',
        teachings: ['Vajrayana practices', 'Terma tradition', 'Dzogchen'],
        works: ['Bardo Thodol (Tibetan Book of Dead)', 'Hidden Termas'],
        quotes: ['"My father is wisdom and my mother is emptiness."'],
        image: 'padmasambhava.jpg'
    },
    {
        id: 'milarepa',
        name: 'Milarepa',
        nameLocal: 'मिलारेपा',
        nameHi: 'मिलारेपा',
        tradition: 'buddhist',
        sampradaya: 'Kagyu',
        period: '1052-1135 CE',
        birthPlace: 'Gungthang, Tibet',
        biography: 'Milarepa is Tibet\'s most celebrated yogi and poet. After a tragic youth where he practiced black magic for revenge, he sought redemption through Buddhism. Under the harsh training of his teacher Marpa, he achieved enlightenment in one lifetime. His spontaneous songs of realization remain beloved.',
        teachings: ['Achieving enlightenment in one lifetime', 'Devotion to guru', 'Cave meditation'],
        works: ['Hundred Thousand Songs of Milarepa'],
        quotes: ['"The affairs of the world will go on forever. Do not delay the practice of meditation."'],
        image: 'milarepa.jpg'
    },
    {
        id: 'atisha',
        name: 'Atisha Dipankara',
        nameLocal: 'अतीश दीपंकर',
        nameHi: 'अतीश दीपंकर',
        tradition: 'buddhist',
        sampradaya: 'Kadampa',
        period: '982-1054 CE',
        birthPlace: 'Vikrampur, Bengal',
        biography: 'Atisha was a great Indian Buddhist master who revived Buddhism in Tibet. A scholar at Vikramashila and Nalanda universities, he was invited to Tibet where he established the Kadampa tradition. His "Lamp for the Path to Enlightenment" became the model for all Lamrim (stages of the path) teachings.',
        teachings: ['Lamrim (Stages of Path)', 'Lojong (Mind Training)', 'Bodhicitta'],
        works: ['Lamp for the Path to Enlightenment', 'Bodhipathapradipa'],
        quotes: ['"The greatest achievement is selflessness."'],
        image: 'atisha.jpg'
    },
    // ========== VEDIC RISHIS ==========
    {
        id: 'valmiki',
        name: 'Maharishi Valmiki',
        nameLocal: 'वाल्मीकि',
        nameHi: 'महर्षि वाल्मीकि',
        tradition: 'hindu',
        sampradaya: 'Vedic Rishi',
        period: 'Treta Yuga',
        birthPlace: 'Ancient India',
        biography: 'Maharishi Valmiki is the author of the epic Ramayana, the first Sanskrit epic poem (Adi Kavya). According to tradition, he was originally a hunter who transformed through the chanting of Rama\'s name. He sheltered Sita during her exile and taught Lava and Kusha. He is revered as the Adi Kavi (first poet).',
        teachings: ['Power of Rama Nama', 'Dharma through storytelling', 'Redemption through devotion'],
        works: ['Ramayana (24,000 shlokas)', 'Yoga Vashishtha (attributed)'],
        quotes: ['"Mara Mara" became "Rama Rama" - thus began my transformation."'],
        image: 'valmiki.jpg'
    },
    {
        id: 'vyasa',
        name: 'Maharishi Vyasa',
        nameLocal: 'व्यास',
        nameHi: 'वेदव्यास',
        tradition: 'hindu',
        sampradaya: 'Vedic Rishi',
        period: 'Dvapara Yuga',
        birthPlace: 'Island in Yamuna River',
        biography: 'Vyasa (Krishna Dvaipayana) is one of the most revered figures in Hindu tradition. He compiled and organized the four Vedas, authored the Mahabharata (the longest epic poem), composed the 18 Puranas, and wrote the Brahma Sutras. He is considered an avatar of Vishnu and one of the Chiranjeevis (immortals).',
        teachings: ['Organization of Vedic knowledge', 'Dharma through narrative', 'Bhakti and Jnana'],
        works: ['Mahabharata', 'Brahma Sutras', '18 Puranas', 'Vedic compilation'],
        quotes: ['"From the sea of the great story, I extracted the essence of the Gita."'],
        image: 'vyasa.jpg'
    },
    {
        id: 'vashishta',
        name: 'Rishi Vashishta',
        nameLocal: 'वसिष्ठ',
        nameHi: 'ऋषि वसिष्ठ',
        tradition: 'hindu',
        sampradaya: 'Vedic Rishi',
        period: 'Vedic Era',
        birthPlace: 'Mind-born son of Brahma',
        biography: 'Rishi Vashishta is one of the Saptarshis (seven great sages) and the Rajguru (royal preceptor) of the Ikshvaku dynasty. He was the guru of Lord Rama and his brothers. He possessed Kamadhenu (wish-fulfilling cow) and his teachings form the Yoga Vashishtha, a profound philosophical text on Advaita.',
        teachings: ['Self-realization', 'Non-dual wisdom', 'Dharmic kingship'],
        works: ['Yoga Vashishtha', 'Vashishtha Dharma Sutra'],
        quotes: ['"This world is neither real nor unreal; it is the projection of consciousness."'],
        image: 'vashishta.jpg'
    },
    {
        id: 'vishwamitra',
        name: 'Rishi Vishwamitra',
        nameLocal: 'विश्वामित्र',
        nameHi: 'ऋषि विश्वामित्र',
        tradition: 'hindu',
        sampradaya: 'Vedic Rishi',
        period: 'Vedic Era',
        birthPlace: 'Kanyakubja',
        biography: 'Vishwamitra was a powerful Kshatriya king who became a Brahmarishi through intense tapasya. He revealed the Gayatri Mantra to the world. He trained young Rama and Lakshmana in divine weapons. His rivalry with Vashishta and his determination to achieve the highest spiritual status are legendary tales.',
        teachings: ['Gayatri Mantra', 'Power of tapasya', 'Transformation through will'],
        works: ['Gayatri Mantra revelation', 'Vishwamitra Samhita'],
        quotes: ['"By the power of tapas, even a king can become a Brahmarishi."'],
        image: 'vishwamitra.jpg'
    },
    {
        id: 'patanjali',
        name: 'Maharishi Patanjali',
        nameLocal: 'पतंजलि',
        nameHi: 'महर्षि पतंजलि',
        tradition: 'hindu',
        sampradaya: 'Yoga',
        period: '2nd century BCE',
        birthPlace: 'Gondia, Maharashtra',
        biography: 'Patanjali is the compiler of the Yoga Sutras, the foundational text of Yoga philosophy. He systematized the ancient practices of yoga into 196 sutras covering the eight limbs (Ashtanga) of yoga. He is also credited with works on Sanskrit grammar (Mahabhashya) and Ayurveda. He is depicted with a serpent form.',
        teachings: ['Ashtanga Yoga (8 limbs)', 'Chitta Vritti Nirodha', 'Samadhi'],
        works: ['Yoga Sutras', 'Mahabhashya'],
        quotes: ['"Yoga is the cessation of the fluctuations of the mind."'],
        image: 'patanjali.jpg'
    },
    {
        id: 'narada',
        name: 'Devarishi Narada',
        nameLocal: 'नारद',
        nameHi: 'देवर्षि नारद',
        tradition: 'hindu',
        sampradaya: 'Vedic Rishi',
        period: 'Eternal',
        birthPlace: 'Mind-born son of Brahma',
        biography: 'Narada is the divine sage who travels between worlds spreading devotion to Vishnu. Always carrying his veena (Mahathi), he is known for his role in many cosmic events through seemingly mischievous interventions that ultimately lead to good. He authored the Narada Bhakti Sutras and is considered the foremost devotee.',
        teachings: ['Para Bhakti (Supreme Devotion)', 'Divine music', 'Cosmic storytelling'],
        works: ['Narada Bhakti Sutras', 'Narada Purana'],
        quotes: ['"Devotion to God is the highest form of love - it is immortal and gives supreme bliss."'],
        image: 'narada.jpg'
    },
    // ========== ACHARYAS & PHILOSOPHERS ==========
    {
        id: 'shankaracharya',
        name: 'Adi Shankaracharya',
        nameLocal: 'आदि शंकराचार्य',
        nameHi: 'आदि शंकराचार्य',
        tradition: 'hindu',
        sampradaya: 'Advaita Vedanta',
        period: '788-820 CE',
        birthPlace: 'Kaladi, Kerala',
        biography: 'Adi Shankaracharya was one of the greatest philosophers of India who consolidated the doctrine of Advaita Vedanta. In his short life of 32 years, he traveled across India, established four maths (Sringeri, Dwarka, Puri, Joshimath), composed numerous works, and revived Hinduism. He is considered an incarnation of Lord Shiva.',
        teachings: ['Advaita (Non-duality)', 'Brahman alone is real', 'World is Maya', 'Atman is Brahman'],
        works: ['Vivekachudamani', 'Atmabodha', 'Bhaja Govindam', 'Brahma Sutra Bhashya'],
        quotes: ['"Brahman is the only truth, the world is illusion, and there is ultimately no difference between Brahman and individual self."'],
        image: 'shankaracharya.jpg'
    },
    {
        id: 'ramanujacharya',
        name: 'Ramanujacharya',
        nameLocal: 'रामानुजाचार्य',
        nameHi: 'रामानुजाचार्य',
        tradition: 'hindu',
        sampradaya: 'Sri Vaishnavism',
        period: '1017-1137 CE',
        birthPlace: 'Sriperumbudur, Tamil Nadu',
        biography: 'Ramanujacharya was the chief proponent of Vishishtadvaita (qualified non-dualism). He reformed Sri Vaishnavism, opened temple worship to all castes, and wrote important commentaries. He is believed to have lived 120 years and established 74 centers of his tradition.',
        teachings: ['Vishishtadvaita', 'Prapatti (Surrender)', 'God has divine qualities', 'Bhakti as the path'],
        works: ['Sri Bhashya', 'Vedarthasangraha', 'Gita Bhashya'],
        quotes: ['"The soul is eternally related to God like a ray to the sun."'],
        image: 'ramanujacharya.jpg'
    },
    {
        id: 'madhvacharya',
        name: 'Madhvacharya',
        nameLocal: 'ಮಧ್ವಾಚಾರ್ಯ',
        nameHi: 'मध्वाचार्य',
        tradition: 'hindu',
        sampradaya: 'Dvaita Vedanta',
        period: '1238-1317 CE',
        birthPlace: 'Pajaka, Karnataka',
        biography: 'Madhvacharya founded the Dvaita (dualist) school of Vedanta, asserting an eternal distinction between God and souls. He established the Krishna temple at Udupi and is considered an incarnation of Vayu. His philosophy influenced the Haridasa movement in Karnataka.',
        teachings: ['Dvaita (Dualism)', 'Five-fold difference', 'Vishnu as Supreme', 'Eternal souls'],
        works: ['Brahma Sutra Bhashya', 'Gita Bhashya', 'Mahabharata Tatparya Nirnaya'],
        quotes: ['"God is eternally different from souls and matter."'],
        image: 'madhvacharya.jpg'
    },
    // ========== MODERN SAINTS ==========
    {
        id: 'ramakrishna',
        name: 'Ramakrishna Paramahamsa',
        nameLocal: 'রামকৃষ্ণ',
        nameHi: 'रामकृष्ण परमहंस',
        tradition: 'hindu',
        sampradaya: 'Modern Saint',
        period: '1836-1886 CE',
        birthPlace: 'Kamarpukur, Bengal',
        biography: 'Sri Ramakrishna was a 19th century mystic and saint who practiced and realized God through multiple religious paths including Hinduism, Islam, and Christianity. A priest at Dakshineswar Kali temple, he attracted a circle of disciples who later spread his message worldwide. His chief disciple was Swami Vivekananda.',
        teachings: ['All religions lead to one God', 'Direct experience of the Divine', 'Jiva is Shiva'],
        works: ['Gospel of Ramakrishna (recorded by disciples)'],
        quotes: ['"As many faiths, so many paths."', '"God can be realized through all paths."'],
        image: 'ramakrishna.jpg'
    },
    {
        id: 'vivekananda',
        name: 'Swami Vivekananda',
        nameLocal: 'স্বামী বিবেকানন্দ',
        nameHi: 'स्वामी विवेकानंद',
        tradition: 'hindu',
        sampradaya: 'Modern Saint',
        period: '1863-1902 CE',
        birthPlace: 'Kolkata, Bengal',
        biography: 'Swami Vivekananda was the chief disciple of Ramakrishna who introduced Indian philosophies of Vedanta and Yoga to the Western world. His address at the 1893 World Parliament of Religions in Chicago made him famous. He founded the Ramakrishna Mission for social service and spiritual development.',
        teachings: ['Practical Vedanta', 'Karma Yoga', 'Service to humanity is service to God', 'Arise, awake!'],
        works: ['Raja Yoga', 'Jnana Yoga', 'Karma Yoga', 'Bhakti Yoga'],
        quotes: ['"Arise, awake, and stop not till the goal is reached."', '"You cannot believe in God until you believe in yourself."'],
        image: 'vivekananda.jpg'
    },
    {
        id: 'ramanamaharshi',
        name: 'Ramana Maharshi',
        nameLocal: 'ரமண மகரிஷி',
        nameHi: 'रमण महर्षि',
        tradition: 'hindu',
        sampradaya: 'Advaita',
        period: '1879-1950 CE',
        birthPlace: 'Tiruchuzhi, Tamil Nadu',
        biography: 'Ramana Maharshi was a sage who achieved self-realization at age 16 through a spontaneous death-experience. He lived at Arunachala hill for 54 years, teaching through silence and the method of self-enquiry ("Who am I?"). He is considered one of the greatest sages of the 20th century.',
        teachings: ['Atma Vichara (Self-enquiry)', 'Who am I?', 'The Self is always realized', 'Silence teachings'],
        works: ['Who Am I?', 'Upadesa Saram', 'Ulladu Narpadu'],
        quotes: ['"Your own Self-Realization is the greatest service you can render the world."', '"Silence is the true teaching."'],
        image: 'ramanamaharshi.jpg'
    },
    {
        id: 'yogananda',
        name: 'Paramahansa Yogananda',
        nameLocal: 'যোগানন্দ',
        nameHi: 'परमहंस योगानंद',
        tradition: 'hindu',
        sampradaya: 'Kriya Yoga',
        period: '1893-1952 CE',
        birthPlace: 'Gorakhpur, Uttar Pradesh',
        biography: 'Paramahansa Yogananda brought Kriya Yoga to the West. His "Autobiography of a Yogi" has introduced millions to Eastern spirituality. He founded the Self-Realization Fellowship (SRF) and Yogoda Satsanga Society. His body showed no signs of decay for 20 days after death.',
        teachings: ['Kriya Yoga', 'Scientific meditation', 'Unity of religions', 'Direct perception of God'],
        works: ['Autobiography of a Yogi', 'God Talks With Arjuna', 'The Second Coming of Christ'],
        quotes: ['"The season of failure is the best time for sowing the seeds of success."'],
        image: 'yogananda.jpg'
    },
    {
        id: 'shirdisaibaba',
        name: 'Shirdi Sai Baba',
        nameLocal: 'शिर्डी साईबाबा',
        nameHi: 'शिर्डी साईबाबा',
        tradition: 'hindu',
        sampradaya: 'Modern Saint',
        period: '1838-1918 CE',
        birthPlace: 'Unknown (lived in Shirdi, Maharashtra)',
        biography: 'Shirdi Sai Baba was a spiritual master revered by both Hindus and Muslims. He lived in a mosque in Shirdi, kept a sacred fire (dhuni), and performed many miracles. His teachings of "Sabka Malik Ek" (One God for all) and "Shraddha Saburi" (faith and patience) continue to inspire millions.',
        teachings: ['Sabka Malik Ek', 'Shraddha and Saburi', 'Love all, serve all', 'Unity of faiths'],
        works: ['Shri Sai Satcharitra (biography by devotees)'],
        quotes: ['"Why fear when I am here?"', '"I am ever living to help those who turn to me."'],
        image: 'shirdisaibaba.jpg'
    },
    {
        id: 'aurobindo',
        name: 'Sri Aurobindo',
        nameLocal: 'শ্রী অরবিন্দ',
        nameHi: 'श्री अरबिंदो',
        tradition: 'hindu',
        sampradaya: 'Integral Yoga',
        period: '1872-1950 CE',
        birthPlace: 'Kolkata, Bengal',
        biography: 'Sri Aurobindo was a philosopher, yogi, and nationalist who developed Integral Yoga for the evolution of human consciousness. Initially a freedom fighter, he later devoted himself to spiritual practice. Along with The Mother, he established the Sri Aurobindo Ashram in Pondicherry.',
        teachings: ['Supramental evolution', 'Integral Yoga', 'Transformation of consciousness', 'Divine Life on Earth'],
        works: ['The Life Divine', 'Savitri', 'Essays on the Gita', 'The Synthesis of Yoga'],
        quotes: ['"All life is yoga."', '"The Divine is everywhere, in all and through all."'],
        image: 'aurobindo.jpg'
    },
    {
        id: 'sivananda',
        name: 'Swami Sivananda',
        nameLocal: 'स्वामी शिवानंद',
        nameHi: 'स्वामी शिवानंद',
        tradition: 'hindu',
        sampradaya: 'Divine Life Society',
        period: '1887-1963 CE',
        birthPlace: 'Pattamadai, Tamil Nadu',
        biography: 'Swami Sivananda was a doctor who became a saint. He founded the Divine Life Society in Rishikesh and wrote over 200 books on yoga, Vedanta, and spiritual practice. He trained many disciples who spread his teachings globally, including Swami Chinmayananda and Swami Satchidananda.',
        teachings: ['Serve, Love, Give, Purify, Meditate, Realize', 'Practical spirituality', 'Integration of Yoga paths'],
        works: ['Sadhana', 'Bliss Divine', 'Practice of Karma Yoga'],
        quotes: ['"An ounce of practice is worth tons of theory."'],
        image: 'sivananda.jpg'
    },
    {
        id: 'prabhupada',
        name: 'A.C. Bhaktivedanta Swami Prabhupada',
        nameLocal: 'প্রভুপাদ',
        nameHi: 'प्रभुपाद',
        tradition: 'hindu',
        sampradaya: 'Gaudiya Vaishnavism',
        period: '1896-1977 CE',
        birthPlace: 'Kolkata, Bengal',
        biography: 'Srila Prabhupada founded the International Society for Krishna Consciousness (ISKCON) at age 69. He traveled to America in 1965 with little money and built a worldwide movement. He translated and commented on major Vaishnava texts and established 108 temples worldwide.',
        teachings: ['Hare Krishna Maha Mantra', 'Bhakti Yoga', 'Krishna consciousness', 'Pure devotional service'],
        works: ['Bhagavad Gita As It Is', 'Srimad Bhagavatam', 'Chaitanya Charitamrita'],
        quotes: ['"Chant Hare Krishna and be happy."'],
        image: 'prabhupada.jpg'
    },
    {
        id: 'anandamayima',
        name: 'Anandamayi Ma',
        nameLocal: 'আনন্দময়ী মা',
        nameHi: 'आनंदमयी मा',
        tradition: 'hindu',
        sampradaya: 'Modern Saint',
        period: '1896-1982 CE',
        birthPlace: 'Kheora, Bengal (now Bangladesh)',
        biography: 'Anandamayi Ma (Blissful Mother) was one of the most prominent spiritual figures of 20th century India. She is said to have attained enlightenment spontaneously without formal training. She traveled across India and was visited by many notable figures including Mahatma Gandhi, Indira Gandhi, and Paramahansa Yogananda.',
        teachings: ['Joyful surrender', 'All paths lead to the One', 'Constant God-remembrance'],
        works: ['Teachings collected by devotees'],
        quotes: ['"Joys and sorrows are time-born and cannot last."', '"Whatever path leads to God is good."'],
        image: 'anandamayima.jpg'
    },
    // ========== WOMEN SAINTS ==========
    {
        id: 'akkamahadevi',
        name: 'Akka Mahadevi',
        nameLocal: 'ಅಕ್ಕ ಮಹಾದೇವಿ',
        nameHi: 'अक्का महादेवी',
        tradition: 'hindu',
        sampradaya: 'Lingayat',
        period: '12th century CE',
        birthPlace: 'Udutadi, Karnataka',
        biography: 'Akka Mahadevi was a 12th century Kannada poet and Bhakti saint devoted to Lord Shiva (Chenna Mallikarjuna). She rejected worldly life, including her marriage to a king, to pursue spiritual liberation. She wandered naked, covered only by her long hair, composing vachanas (prose poems).',
        teachings: ['Complete devotion to Shiva', 'Rejection of materialism', 'Spiritual equality of women'],
        works: ['Vachanas (430+ poems)'],
        quotes: ['"I have fallen in love with the beautiful one, who has no death, no fear, no caste."'],
        image: 'akkamahadevi.jpg'
    },
    {
        id: 'lalded',
        name: 'Lalleshwari (Lal Ded)',
        nameLocal: 'लल्लेश्वरी',
        nameHi: 'लल्लेश्वरी',
        tradition: 'hindu',
        sampradaya: 'Kashmir Shaivism',
        period: '1320-1392 CE',
        birthPlace: 'Pandrethan, Kashmir',
        biography: 'Lalleshwari (Lal Ded) was a Kashmiri mystic and poet who composed vaakhs (spiritual verses) that are revered by both Hindus and Muslims. Despite facing abuse from her in-laws, she left home to wander as a spiritual teacher. Her poetry speaks of the inner spiritual journey.',
        teachings: ['Inner spiritual search', 'Shiva in the heart', 'Unity of Hindu-Muslim teachings'],
        works: ['Lal Vaakh (Verses)'],
        quotes: ['"I searched for Shiva everywhere, finally found Him within myself."'],
        image: 'lalded.jpg'
    },
    {
        id: 'muktabai',
        name: 'Sant Muktabai',
        nameLocal: 'संत मुक्ताबाई',
        nameHi: 'संत मुक्ताबाई',
        tradition: 'hindu',
        sampradaya: 'Varkari',
        period: '1279-1297 CE',
        birthPlace: 'Apegaon, Maharashtra',
        biography: 'Muktabai was the youngest of the four siblings of the great Varkari family (Nivrutti, Dnyaneshwar, Sopan, and Muktabai). Despite her young age, she was spiritually advanced. She tamed the violent Changdev by demonstrating her powers. She authored profound abhangas.',
        teachings: ['Detachment', 'Spiritual power', 'Devotion to Vitthal'],
        works: ['Tatiche Abhang (40+ verses)'],
        quotes: ['"The realized soul sees no difference between gold and dust."'],
        image: 'muktabai.jpg'
    },
    // ========== REGIONAL SAINTS ==========
    {
        id: 'shankardev',
        name: 'Srimanta Shankardev',
        nameLocal: 'শঙ্কৰদেৱ',
        nameHi: 'शंकरदेव',
        tradition: 'hindu',
        sampradaya: 'Ekasarana Dharma',
        period: '1449-1568 CE',
        birthPlace: 'Bordowa, Assam',
        biography: 'Srimanta Shankardev was a 15th-16th century Assamese polymath who founded the Ekasarana Dharma (single refuge in Vishnu). He composed devotional songs (borgeet), created the Sattriya dance form, and established namghars (prayer halls). He translated the Bhagavata Purana into Assamese.',
        teachings: ['Ekasarana (Single refuge in God)', 'Naam (Chanting)', 'Community worship'],
        works: ['Kirtana Ghosa', 'Borgeets', 'Ankiya Naat'],
        quotes: ['"Taking refuge in one God (Krishna) is the path to liberation."'],
        image: 'shankardev.jpg'
    },
    {
        id: 'basavanna',
        name: 'Basavanna',
        nameLocal: 'ಬಸವಣ್ಣ',
        nameHi: 'बसवण्णा',
        tradition: 'hindu',
        sampradaya: 'Lingayat',
        period: '1131-1167 CE',
        birthPlace: 'Bagewadi, Karnataka',
        biography: 'Basavanna was a 12th century philosopher, statesman, and social reformer who founded Lingayatism. He was prime minister of the Kalachuri dynasty. He rejected caste discrimination, promoted women\'s equality, and established the Anubhava Mantapa, a spiritual parliament where people of all backgrounds shared wisdom.',
        teachings: ['Kayaka (Work is worship)', 'Rejection of caste', 'Equality of all devotees'],
        works: ['Vachanas'],
        quotes: ['"Work is worship. Earnings through honest work is temple of God."'],
        image: 'basavanna.jpg'
    },
    {
        id: 'thiruvalluvar',
        name: 'Thiruvalluvar',
        nameLocal: 'திருவள்ளுவர்',
        nameHi: 'तिरुवल्लुवर',
        tradition: 'hindu',
        sampradaya: 'Tamil Poet-Saint',
        period: '1st century BCE - 5th century CE',
        birthPlace: 'Mylapore, Chennai (traditionally)',
        biography: 'Thiruvalluvar was the author of the Thirukkural, a classic Tamil text on ethics, political and economic matters, and love. The work consists of 1330 couplets (kurals) organized into 133 chapters. His teachings on virtue, wealth, and love are considered universal wisdom.',
        teachings: ['Dharma (Virtue)', 'Artha (Wealth)', 'Kama (Love)', 'Universal ethics'],
        works: ['Thirukkural'],
        quotes: ['"All beings are born equal. The only distinction is by their deeds."'],
        image: 'thiruvalluvar.jpg'
    },
    {
        id: 'swaminarayan',
        name: 'Bhagwan Swaminarayan',
        nameLocal: 'સ્વામિનારાયણ',
        nameHi: 'स्वामीनारायण',
        tradition: 'hindu',
        sampradaya: 'Swaminarayan',
        period: '1781-1830 CE',
        birthPlace: 'Chhapaiya, Uttar Pradesh',
        biography: 'Bhagwan Swaminarayan (Sahajanand Swami) founded the Swaminarayan Sampradaya. He traveled across India on foot, reformed many social evils, and built magnificent temples. His followers consider him a manifestation of God. The BAPS organization continues his work worldwide.',
        teachings: ['Dharma, Bhakti, Jnana, Vairagya', 'Satsang', 'Moral living'],
        works: ['Shikshapatri', 'Vachanamrut'],
        quotes: ['"One should offer devotion to God, having an understanding of His greatness."'],
        image: 'swaminarayan.jpg'
    },
    {
        id: 'amma',
        name: 'Mata Amritanandamayi',
        nameLocal: 'അമ്മ',
        nameHi: 'माता अमृतानंदमयी',
        tradition: 'hindu',
        sampradaya: 'Modern Saint',
        period: 'Born 1953 CE',
        birthPlace: 'Parayakadavu, Kerala',
        biography: 'Mata Amritanandamayi, known as Amma (Mother), is called the "Hugging Saint" for her practice of embracing devotees. She has hugged over 40 million people worldwide. Her humanitarian organization, Embracing the World, runs hospitals, schools, and disaster relief programs. She teaches selfless love and compassion.',
        teachings: ['Selfless love', 'Service (Seva)', 'Compassion for all beings'],
        works: ['Numerous discourses compiled by devotees'],
        quotes: ['"Love is our true essence."', '"In this universe, it is love that binds everything together."'],
        image: 'amma.jpg'
    }
];

// Export for use in script.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { TRADITIONS, SAINTS };
}
